version: 2

jobs:
  Tests:
    docker: [{ image: 'circleci/node:10' }]
    steps:
      - checkout
      - run: npm i
      - run:
          name: Jest suite
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  Bundlesize:
    docker: [{ image: 'circleci/node:8' }]
    steps:
      - checkout
      - run: npm i
      - run: npm run bundlesize

workflows:
  version: 2
  Build and Test:
    jobs:
      - Tests
      - Bundlesize
